<PropertyGroup>
  <JavaSdkDirectory Condition="Exists('C:\Program Files\Microsoft\OpenJDK\jdk-*')">C:\Program Files\Microsoft\OpenJDK\jdk-*;</JavaSdkDirectory>
  <JavaSdkDirectory Condition="Exists('C:\Program Files\Java\jdk-*')">C:\Program Files\Java\jdk-*;</JavaSdkDirectory>
  <JavaSdkDirectory Condition="Exists('C:\Program Files\Java\jre-*')">C:\Program Files\Java\jre-*;</JavaSdkDirectory>
  <JavaSdkDirectory Condition="Exists('C:\Program Files\Oracle\Java\javapath\')">C:\Program Files\Oracle\Java\javapath\;</JavaSdkDirectory>
  <JavaSdkDirectory Condition="Exists('/usr/lib/jvm/java-*')">/usr/lib/jvm/java-*;</JavaSdkDirectory>
</PropertyGroup>